

export default {
    '400': { cause: 'Bad Request' },
    '401': { cause: 'Unauthorized' },
    '403': { cause: 'Forbidden' },
    '404': { cause: 'Not Found' },
    '408': { cause: 'Request Timeout' },
    '409': { cause: 'Conflict' },
    '410': { cause: 'Gone' },
    '411': { cause: 'Length Required' },
    '412': { cause: 'Precondition Failed' },
    '413': { cause: 'Payload too large' },
    '414': { cause: 'URI too long' },
    '415': { cause: 'Unsupported Media Type' },
    '418': { cause: 'I am a teapot' },
    '421': { cause: 'Misdirected request' },
    '422': { cause: 'Unprocessable Entity', },
    '428': { cause: 'Precondition failed' },
    '429': { cause: 'Too many requests' },
    '500': { cause: 'Internal Server Error' },
    '501': { cause: 'Not Implemented' },
    '502': { cause: 'Bad Gateway' },
    '503': { cause: 'Service Unavailable' },
    '504': { cuase: 'Gateway timeout' },
    '505': { cause: 'Http version not supported' },
    '507': { cause: 'Insufficient Storage' },
    '508': { cause: ''},
    '509': { },
    '510': { },
    '511': { }
}